# Site settings
description: Blog Pessoal
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://localhost:4000" # the base hostname & protocol for your site 

# User settings
username: Jefferson Maran
user_description: Desenvolvedor Pai Marido
user_title: Blog Pessoal
email: jefferson.maran@gmail.com
twitter_username: jefferson_maran
github_username: jeffmaran
gplus_username:  jeffersonmaran
disqus_username: jefferson_maran

# Build settings
markdown: kramdown
# highlighter: pygments
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: tutoriais
    url: /tutoriais
  - title: Tags
    url: /tags
  - title: Sobre
    url: /sobre

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
